spring:
  application:
    name: Generator

management:
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    metrics:
      export:
        url: http://localhost:4317/v1/metrics
        step: 10s

  otel:
    exporter:
      otlp:
        endpoint: http://localhost:4317

