global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Prometheus auto-monitoramento
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

#  # Spring Boot aplicação
#  - job_name: 'generator'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
##      - targets: ['host.docker.internal:8080']  # Se estiver usando Docker
#       - targets: ['ip:8080']        # IP direto da máquina

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Nome do serviço no docker-compose

  # Métricas internas do OpenTelemetry Collector
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
