name: Java CI with Gradle

on:
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: Set up Gradle with caching
        uses: gradle/actions/setup-gradle@v3

      - name: Validate dependencies
        run: ./gradlew dependencies --no-daemon

      - name: Build (compile)
        run: ./gradlew assemble --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon --scan
        continue-on-error: false

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon --scan

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest --no-daemon --scan

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest --no-daemon --scan

      - name: Run Jacoco
        run: ./gradlew jacocoTestReport --no-daemon --scan

      - name: Full Build (without redundant tasks)
        run: ./gradlew build --no-daemon -x test -x checkstyleMain -x checkstyleTest -x pmdMain -x pmdTest -x jacocoTestReport --scan

        
      - name: Upload Jacoco report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle

      - name: Upload PMD report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: build/reports/spotbugs