name: Common Gradle Steps

on:
  workflow_call:
    inputs:
      gradle_task:
        required: true
        type: string

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties', '**/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Task
        run: ./gradlew ${{ inputs.gradle_task }} --no-daemon --scan