name: CI gradle

on:
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  dependencies:
    uses: ./.github/workflows/gradle-common.yml
    with:
      gradle_task: 'dependencies'

  checkstyle:
    uses: ./.github/workflows/gradle-common.yml
    with:
      gradle_task: 'checkstyleMain checkstyleTest'

  pmd:
    uses: ./.github/workflows/gradle-common.yml
    with:
      gradle_task: 'pmdMain pmdTest'

  spotbugs:
    uses: ./.github/workflows/gradle-common.yml
    with:
      gradle_task: 'spotbugsMain spotbugsTest'

  tests:
    uses: ./.github/workflows/gradle-common.yml
    with:
      gradle_task: 'test'

  coverage:
    uses: ./.github/workflows/gradle-common.yml
    with:
      gradle_task: 'jacocoTestReport'

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    needs:
      - checkstyle
      - dependencies
      - tests
      - coverage
      - pmd
      - spotbugs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties', '**/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Full Build (without redundant tasks)
        run: ./gradlew build --no-daemon -x test -x checkstyleMain -x checkstyleTest -x pmdMain -x pmdTest -x jacocoTestReport --scan

  reports:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    needs:
      - build
      - coverage
      - tests
      - checkstyle
      - pmd
      - spotbugs

    steps:
      - name: Upload Jacoco report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle

      - name: Upload PMD report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: build/reports/spotbugs